### ISSUE TITLE
Using Categorical Annotations with Multiple Categories in STAAR.

### ISSUE THREAD

**Issue by HasanA75** [xihaoli/STAAR#14]
Hello Xihao.

How should categorical annotations that have more than 2 categories be used in STAAR? I had two choices below. Could you please let me know which would work?

1. Turn these categorical annotations into a single binary variable
2. Implement several binary variables to denote each level in the categorical annotations.
3. Treat the categories as continuous variables and generate a Phred score for the annotation.
4. Add in the categories and scores as-is into STAAR.

Thank you.

**Comment by xihaoli** [comment]
Hi Hasan,

Thanks for your question. Based on your description, all options should work except for the 4th one, since the input annotation values of the STAAR function are assumed to be on Phred scale rather than raw categories. One thing to note is that if you want to input dichotomous values (0/1) as the weights (e.g. for your option 1), then you are essentially "removing" variants in the class "0" from the variant set, when calculating the P value weighted by this specific annotation.

Best,
Xihao

**Comment by HasanA75** [comment]
Thank you.
